### PR TITLE
Fix tests after isodoc update

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma-ogc/issues/36

Not ready for a merge right now, just tests fixed

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
Current gem produces `doc` which is just plain text, IDK how right it is, but AFAIK it should be some binary, also Pages (default OSX doc app and Libre Office cannot open it)
[test.doc.txt](https://github.com/metanorma/metanorma-ogc/files/3243089/test.doc.txt)

**Comment by opoudjis** [comment]
I cannot check now, but doc file is generated as text (MIME file with attachments), it just isn't supposed to have a .txt filename suffix.

**Comment by CAMOBAP795** [comment]
> doc file is generated as text (MIME file with attachments)

Is that expected behavior?

> it just isn't supposed to have a .txt filename suffix.

GitHub doesn't allow `doc` attachment this is why I changed it to `doc.txt`

**Comment by opoudjis** [comment]
Yes, it has been a MIME file since the beginning,  and not  a binary.

**Comment by CAMOBAP795** [comment]
@opoudjis ok

**Pull request closed without merging**
