### PR TITLE
Fixate node version to 8.x

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma/issues/46

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 specs are all failing here somehow...

**Comment by CAMOBAP795** [comment]
@ronaldtse they are not related to this PR, fix is easy, I can proceed with fix just let me know

**Comment by ronaldtse** [comment]
Looks like the failure is just about whitespaces in HTML. If we use the `equivalent-xml` RSpec helper it might already pass:

```
       @@ -1,15 +1,14 @@
       - <body lang="EN-US" link="blue" vlink="#954F72" xml:lang="EN-US" class="container">
       -<div class="title-section">
       -  <p>&#160;</p>
       -</div>
       -<br/>
       -<div class="prefatory-section">
       -  <p>&#160;</p>
       -</div>
       -<br/>
       -<div class="main-section">
       -
       - <br/>
       +<body lang="EN-US" link="blue" vlink="#954F72" xml:lang="EN-US" class="container">
       +    <div class="title-section">
       +      <p>&#160;</p>
       +    </div>
       +    <br/>
       +    <div class="prefatory-section">
       +      <p>&#160;</p>
       +    </div>
       +    <br/>
       +    <div class="main-section">
       +      <br/>

@@ -42,23 +41,23 @@
                <p id="E">Text</p>
              </div>
              <div id="D1">
       -         <h1>2.&#160; Conformance</h1>
       -         <p id="E1">Text</p>
       -     </div>
       +        <h1>2.&#160; Conformance</h1>
       +        <p id="E1">Text</p>
       +      </div>
...
       -<div id="I">
       -   <h2>4.1. Normal Terms</h2>
       -   <p class="TermNum" id="J">4.1.1.</p>
       -   <p class="Terms" style="text-align:left;">Term2</p>
       +<div id="I"><h2>4.1. Normal Terms</h2>
        
       - </div><div id="K"><h2>4.2. Symbols and abbreviated terms</h2>
       -   <dl><dt><p>Symbol</p></dt><dd>Definition</dd></dl>
       - </div></div>
       +     <p class="TermNum" id="J">4.1.1.</p>
       +     <p class="Terms" style="text-align:left;">Term2</p>
       +
       +   </div><div id="K"><h2>4.2. Symbols and abbreviated terms</h2>
       +     <dl><dt><p>Symbol</p></dt><dd>Definition</dd></dl>
       +   </div></div>
...
```

**Comment by CAMOBAP795** [comment]
> Looks like the failure is just about whitespaces in HTML

@ronaldtse I think there is logic changed or input data changed because the number of paragraph/title was changed

**Comment by ronaldtse** [comment]
@CAMOBAP795  aha yes you're right! The only "real" change I see is:

```
 @@ -69,23 +68,23 @@
                </dl>
              </div>
              <div id="M">
       -        <h1>6.&#160; Clause 4</h1>
       -        <div id="N">
       -   <h2>6.1. Introduction</h2>
       - </div>
       -        <div id="O">
       -   <h2>6.2. Clause 4.2</h2>
       - </div>
       +        <h1>7.&#160; Clause 4</h1>
       +        <div id="N"><h2>7.1. Introduction</h2>
       +
       +   </div>
       +        <div id="O"><h2>7.2. Clause 4.2</h2>
       +
       +   </div>
```

Where the clause number is different.

If possible, can you first change to use a proper XML comparison tool (`equivalent-xml`), and if there are any issues remaining, maybe @opoudjis needs to confirm the right fix.

**Comment by CAMOBAP795** [comment]
Test data looks ok, Issue was introduced in 935d1c2304b0320e0ed58ab2da0b8e6f61b11ade

*Also, I noticed that code in `lib/isodoc/ogc/*_convert.rb` contains many duplications https://codeclimate.com/github/metanorma/metanorma-ogc/issues

**Comment by ronaldtse** [comment]
@camobap795 please feel free to help refactor the code (make sure the class names are not changed otherwise it might not be compatible with the rest of the gems)

**Comment by CAMOBAP795** [comment]
I did some refactoring, but in my opinion general approach didn't look good, it more looks like a workaround (or hack), and looks like the right place for these changes is `isodoc`

@ronaldtse @opoudjis may I ask you to carefully review my changes

**Comment by opoudjis** [comment]
Clause numbering: yes, I introduced a bugfix to ensure that Conformance was counted as a section for numbering before the main set of clauses (after Terms).

The redundancy between converters under isodoc is pervasive throughout Metanorma.

To my astonishment, your refactor works. I didn't do the refactor for all this time, because of the fact that a module cannot override a class's methods without going via base.instance_eval: http://tech.tulentsev.com/2012/02/ruby-how-to-override-class-method-with-a-module/ . 

But because the converters specific to each flavour are brand new classes, the module overrides shared by them as common behaviour do work after all. Huh. I was much too timid about this.

**Comment by opoudjis** [comment]
This means that *all* metanorma gems should be refactored in this way.

@CAMOBAP795, do you feel like doing so? The same refactor would happen in all metanorma-*/lib/isodoc converters, but for metanorma-standoc (which does not have an isodoc realisation).

**Comment by opoudjis** [comment]
On the other hand, I must angrily reject https://github.com/metanorma/metanorma-ogc/pull/32/commits/d88b8f343e11d7e79346acf631d2a0c0479eb410 . You are bypassing the assignment of clause labels in preprocessing through `@anchors` (`clause_name(get_anchors[c['id']][:label], c&.at(ns("./title"))&.content, s, nil)`), and that is unacceptable: if the anchors assignment isn't working, then the cross-references to titles are broken anyway, so your fix is a kludge. I am going to undo this, and fix it properly at the level of cross-references, which is where all section labels are meant to be encoded.

**Comment by opoudjis** [comment]
In fact, I had refactored isodoc already to deal with this issue: https://github.com/metanorma/isodoc/commit/51711181b1f15c2a314b335f81b4e849a4130e96

@CAMOBAP795, the dependence of gems on other gems in this stack is annoying, but if you're unaware of it, you break things. Please (a) ask me before doing this kind of thing, (b) always check for recent tweaks to isodoc and metanorma-standoc before doing this kind of thing.

**Comment by CAMOBAP795** [comment]
@opoudjis sorry for the inconvenience, next time I will sync with you

**Comment by opoudjis** [comment]
Given this kind of dependency, I'd suggest that I do a release of all gems first, and then if you're interested, you can do the same refactoring.

It's a lot of work, and I'm sorry. I did try for almost all gems to keep the shared methods for Word and HTML in the same place in the classes, but NIST (which is work in progress) has not been cleaned up.

I'm sorry I didn't realise a module refactor would work; I got burned from trying to do it within isodoc (where I can't, because that's where the classes are being defined to begin with.)

**Comment by opoudjis** [comment]
I'm accepting the merge, but this will now break in travis until isodoc is released.

**Pull request merged**
